version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  images_microservice:
    build:
      context: ./images_microservice
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env-non-dev
    command: sh -c "gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "7777:8000"
    volumes:
      - ./images_microservice/static:/images_microservice/static

  celery:
    build:
      context: ./images_microservice
    depends_on:
      - redis
      - images_microservice
    env_file:
      - .env-non-dev
    volumes:
      - ./images_microservice/static:/images_microservice/static
    command: sh -c "celery -A tasks.celery_app:celery_app worker --loglevel=info --pool=threads"
    restart: unless-stopped
