version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  images_microservice:
    build:
      context: ./images_microservice
      dockerfile: Dockerfile
    depends_on:
      - redis
      - celery
    env_file:
      - .env-non-dev
    command: sh -c "gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - "7777:8000"

  celery:
    build:
      context: ./images_microservice
    depends_on:
      - redis
    env_file:
      - .env-non-dev
    command: sh -c "celery -A tasks.celery_app:celery_app worker --loglevel=info"
    restart: unless-stopped

# services:
#   app:
#     image: app
#     build:
#       context: ./images_microservice
#     container_name: app
#     env_file:
#       - .env-non-dev
#     depends_on:
#       redis:
#         condition: service_started
#     command: >
#       sh -c "gunicorn images_microservice.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
#     ports:
#       - "7777:8000"

#   celery:
#     image: celery_image
#     build:
#       context: ./images_microservice
#     container_name: celery
#     env_file:
#       - .env-non-dev
#     depends_on:
#       - redis
#     command: >
#       sh -c "celery -A images_microservice.tasks.celery_app:celery_app worker --loglevel=info"

#   redis:
#     image: redis:alpine
#     container_name: redis
#     ports:
#       - "6379:6379"
