# Generated by Django 5.1.2 on 2024-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zip_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
