# Generated by Django 5.1.2 on 2024-11-21 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=250, verbose_name="Категория"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "unique_together": {("slug", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("brand", models.CharField(max_length=250, verbose_name="Бренд")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("slug", models.SlugField(max_length=250, verbose_name="URL")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=99.99,
                        max_digits=7,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="products/products/default.jpeg",
                        upload_to="images/products/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Наличие"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.JSONField(
                        blank=True, default={}, verbose_name="Температура"
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(blank=True, default={}, verbose_name="Габариты"),
                ),
                (
                    "cooled_volume",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Охлаждаемый объём"
                    ),
                ),
                (
                    "energy_consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        verbose_name="Энергопотребление в кВт",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.product",),
        ),
    ]
