# Generated by Django 5.1.2 on 2024-12-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("slug", models.SlugField(max_length=250, verbose_name="URL")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="blog/blog/default.jpeg",
                        upload_to="images/blog/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blogs",
                        to="products.product",
                        verbose_name="Продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["-created_at"],
            },
        ),
    ]
